# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

basepath = "."

[env]
    cv = "{l10n_base}/web/locales/common-voice/{locale}/"
    ss = "{l10n_base}/web/locales/spontaneous-speech/{locale}/"

[[paths]]
    reference = "web/locales/common-voice/en/**"
    l10n = "{cv}**"

[[paths]]
    reference = "web/locales/spontaneous-speech/en/**"
    l10n = "{ss}**"
